export const languages = [
    {
        code: 0,
        lang: "Hebrew",
        short: "He",
        img: "",
        dict: {
            ENTER_PHONE: "פשוט להכניס את מספר הטלפון שלך:",
            YOUR_PHONE: "הטלפון שלך",
            USER_PHONE: "טלפון המשתמש",
            TASK_MESSAGE_START: "אנחנו ב ",
            STEPBY: "stepby ",
            TASK_MESSAGE_END: "בעניין להפוך את תהליכי העבודה שלך לפשוטים ונוחים יותר - לך וללקוחות שלך. בואו נתחיל...",
            SUBMIT_CODE: "שלחנו קוד אימות, זמן מעולה להקליד אותו:",
            SEND_CODE: "שלחנו למספר",
            NEW_CODE: "שלח קוד שוב",
            SOMETHINGS_WRONG: "משהו לא סבבה?",
            PERSONAL_INFORMATION: "מספר טלפון זה סבבה, אבל בכל זאת, בני אדם...",
            FIRST_NAME: "שם פרטי",
            LAST_NAME: "שם משפחה",
            EMAIL: "אימייל",
            PHONE: "טלפון",
            BUSINESS_NAME_HEADER: "באיזה שם הלקוחות שלך מכירים את העסק שלך?",
            YOUR_BUSINESS_NAME: "שם העסק שלך",
            EXTERIOR_DESIGN: "עיצוב פנים",
            WEB_DEVELOPMENT: "בניית אתרים",
            DIGITAL_MARKETING: "שיווק דיגיטלי",
            FITNESS_TRAINING: "אימון כושר גופני",
            OTHER: "אחר",
            PROJECTS: "פרויקטים",
            TEMPLATES: "תבניות",
            ALL: "הכל",
            MY_CARE: "בטיפול שלי",
            CARE: "בטיפול...",
            WAITING_CUSTOMER: "ממתין ללקוח",
            FIRST_AND_LAST_NAME: "שם פרטי ומשפחה",
            AREAS_PRACTICE: "תחומי עיסוק",
            LOGGING_OFF: "התנתקות",
            LETS_GO: "פשוט, בוא נתחיל",
            ICON: "האייקון",
            CALL_YOU: "...קורא לך",
            TEMPLATES_NAME: "שם התבנית החדשה ",
            TEMPLATES_TEXT: "זה שם שמיועד לשימוש פנימי שלך (הלקחות שלך לא יהיו חשופים אליו)",
            SAVE: "שמירה",
            NEW_TEMPLATE: "תבנית חדשה ",
            NEW_TEMPLATE_HEADER: "אפיון ועיצוב אתר תדמית מורכב",
            CREATION_MODE: "מצב יצירה ועריכת תדמית",
            STEP_BY_STEP: "שלב אחר שלב",
            PRESS_ON: "לחיצה על",
            ADD_STEP: "כדי להוסיף רשימת שלבים",
            GATHERING_INSPIRATION: "איסוף השראות ומתחרים",
            TREATMENT: "בטיפול",
            CUSTOMER: "הלקוח",
            MYE: "שלי",
            SHOW_ALL: "להציג הכל",
            MORE_TO_ADD: "יש מה להוסיף?",
            SHOW_MORE_DTAT: "כדי לאסוף או להציג מידע נוסף",
            WRONG_PONE: "מספר טלפון לא נכון",
            SEND_CODE_AGAIN: " שלחנו שוב ",
            SEND_CODE_AGAIN_END: " למספר  ",
            NEW_CUSTOMER: "לקוח חדש",
            NEW_PROJECT: "פרויקט חדש ללקוח קיים",
            FULL_NAME_CUSTOMER: "שם מלא של הלקוח",
            SAVE_CUSTOMER: "שמירת לקוח חדש",
            START: "מתחילים?",
            START_P: "כדי להתחיל פרוייקט עבור לקוח שיצת במערכת, עליך לבחור תבנית מרשימת התבניות וללחוץ על האייקון המשולש (Play) בפינה השמאלית התחתונה של המסך התבנית שבחרתה",
            YOUR_TEMPLATE: "התבנית שלך...",
            UNDERSTOOD: "הבנתי, יאללה לבחירת תבנית ...",
            DISTRIBUTION: "הפצה",
            GENERAL: "כללי",
            SOME_CUSTOMER: "לקוח מסוים",
            STEP_NAME: "שם השלב",
            DESCRIPTION: "תיאור",
            TEXT_STEP: "לאחר שמירה אפשר בקלות להעשיר את השלב בתמונות וקבצים(ובעתיד הקרוב בעוד הרבה יותר...)",
            SAVE_AND_CREATE: "שמירה + יצירת שלב נוסף",
            MY: "שלי",
            EMAIL_ID: "אימייל או ID",
            DUPLICATE_TEMPLATE: "שכפול תבנית זאת",
            DELETE_TEMPLATE: "מחיקת תבנית",
            DUPLICATE_STEP: "שכפול שלב זה",
            DELETE_STEP: "מחיקת שלב",
            SIMPLE_ANS: "תשובה פשוטה",
            UPLOAD: "העלאת קובץ / צילום",
            CHOOSE: "בחירה מרשימה",
            RATING: "דירוג",
            PAYMENT: "דרישת תשלום",
            SOON: "בקרוב",
            MORE_DETAILS: "הצגת מידע נוסף ללקוח",
            IMG: "תמונה",
            FILE_PDF: "קובץ PDF",
            VIDEO: "סירטון",
            PERMISSION: "רשות",
            REQUIRED: "חובה",
            DESCRIPTION_FILE: "תיאור קובץ",
            DESCRIPTION_IMG: "תיאור תמונה",
            DESCRIPTION_PDF: "תיאור למסמך",
            FILE_LOAD: "טעינת קובץ",
            DESCRIPTION_ASK: "השאלה שלך",
            ASK_REQ: "שאלת חובה",
            ASK_PER: "שאלת רשות",
            CONTINUED: "המשך",
            NEW: "חדש",
            EXIST: "קיים",
            CREATE_PROJECT: "יצירת פרוייקט",
            WE_SAFE: "אנחנו בטוחים?",
            EMAIL_UPDATE: "אימייל עדכון ישלח ל",
            NEXT_STEP: ":השלב הבא",
            DONE: "כן, סיימתי!",
            COMPETITOR: "מי המתחרה העיקרי שלך באינטרנט?",
            UPLOAD_IMG: "העלאת צילומי מסך של מתחרים טובים",
            EDIT_NAME: "עריכת שם פרוייקט",
            COMPLET_PROJECT: "סימון הפרויקט כ'כהושלם'",
            DEL_PROJECT: "מחיקת פרויקט",
            REQ_STEP: "הגדרה כ'צעד נוכחי'",
            LONG_ASK: "שאלה ארוכה",
            SHORT_ASK: "שאלה קצרה",
            FINISH_PROJECT: "הפרויקט הזה מאחורינו!",
            COMPLET: "הושלם",
            CURRENT_STEP: "השלב הנוכחי",
            AWAIT: "כרגע ממתינים לך",
            CARE_OF: "כרגע בטיפול של",
            NO: "לא",
            TO_THE_WAY: "יוצאים לדרך!",
            DISPERSTION: "תפוצה",
            SUB_TITLE_SPLASH:"הלקוחות שלך, היעילות שלנו"

        }
    },
]